---
  - name: Install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Start Apache (Ubuntu)
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Start MySQL Service (Ubuntu)
    service:
      name: mysql
      state: started
      enabled: true
    when: ansible_distribution == "Ubuntu"

  - name: Install MySQL package  (Ubuntu)
    apt:
      name: mysql-server
      state: present
    when: ansible_distribution == "Ubuntu"

