---
  - name: Setting up Influxdb repo for Centos
    ansible.builtin.copy:
      dest: /etc/yum.repos.d/influxdb.repo
      content: |
              [grafana]
              name = grafana
              baseurl = https://packages.grafana.com/oss/rpm
              enabled = 1
              gpgcheck = 1
              gpgkey = https://packages.grafana.com/gpg.key
              sslverify=1
              sslcacert=/etc/pki/tls/certs/ca-bundle.crt
    when: ansible_distribution == "CentOS"

  - name: Installing software for grafana (CentOS)
    ansible.builtin.dnf:
      name:
       - grafana
       - vim
    when: ansible_distribution == "CentOS"

  - name: Starting grafana (CentOS)
    ansible.builtin.systemd:
      name: grafana-server
      enabled: yes
      state: restarted
    when: ansible_distribution == "CentOS"
